name = "LanguageModelingDatasets"
uuid = "3c2ae550-0c1b-11ea-1219-79c2f5e36aab"
authors = ["David Ellison <davidehellison@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"
DataDeps = "0.6, 0.7"

[deps]
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]